from fastapi import FastAPI
import uvicorn
import os

app = FastAPI()

port = int(os.getenv('PORT', 8000))
reload = bool(os.getenv('RELOAD', 1))
host=str(os.getenv('HOST','0.0.0.0'))

@app.get('/')
def Home():
    return "Service is Running..."

# This is meant to 
@app.get('/options-attributes')
def OptionsAttrubutes():
    attributes = ['attribute_1', 'attribute_2', 'attribute_3', 'attribute_4', 'attribute_5']
    return attributes


# Rule Model

# export type Rule = {
#     id?: number | null,
#     title: string | null,
#     description?: string | null,
#     rule: object[] | null,
#     weight: number | null,
#     autogenerated: boolean,
#     active: boolean,
#     createdAt: string | null
# }



if __name__ == "__main__":
    print('port => ', port)
    print('reload => ', reload)
    print('host => ', host)
    uvicorn.run('main:app', port=port, reload=reload, host=host)
