from fastapi import FastAPI
import uvicorn
import os
from fastapi.responses import RedirectResponse

app = FastAPI()

port = int(os.getenv('PORT', 8000))
reload = bool(os.getenv('RELOAD', 1))
host=str(os.getenv('HOST','0.0.0.0'))

# Constants
ARITHMETIC = 'ARITHMETIC_OPERATORS'
COMPARATIVE = 'COMPARATIVE_OPERATORS'
LOGICAL = 'LOGICAL_OPERATORS'

ARITHMETIC_OPERATORS = ['+','-','*','/','%','^']
COMPARATIVE_OPERATORS = ['<','>','<=','>=','==']
LOGICAL_OPERATORS = ['AND','OR','NOT']

# General Methodsk

# To generate the list of attributes of the transaction
def get_attributes():
    attributes = ["fraud", "trx_datetime", "trx_unique_id", "type_call", "transaction_type", "trx_amount_total", "md_payer_document_type", "md_payer_phone_number", "md_payer_document_number", "md_payer_email", "pay_card_iin", "pay_card_md_bank", "pay_card_md_brand", "pay_card_md_on_us", "pay_card_md_channel", "md_trx_channel", "md_trx_pos_condition", "md_trx_operation_code", "md_pay_bank_account_owner_document_type", "md_pay_bank_account_finantial_inst_id", "md_pay_bank_account_compensation_inst_id", "md_support_trace_id", "md_trx_reconciliation_id", "md_payer_country", "response_trx_acquirer", "merchant_on_us", "md_merchant_store_id", "md_merchant_terminal_id", "md_merchant_category_code", "md_merchant_submerchant_city", "md_merchant_submerchant_name", "md_merchant_acquirer_submerchant_id", "md_merchant_tributary_document_type", "md_pay_method", "trx_installments_number"]
    return attributes

def get_operators(type):
    if type == ARITHMETIC:
        return ARITHMETIC_OPERATORS
    elif type == COMPARATIVE:
        return COMPARATIVE_OPERATORS
    elif type == LOGICAL:
        return LOGICAL_OPERATORS
    else:
        return []

# API Endpoints
@app.get('/')
def Home():
    response = RedirectResponse(url='/docs')
    return response

# This is meant to return attributes to show in the dropdown in the UI
@app.get('/attributes')
def Attributes():
    attributes = get_attributes()
    return attributes

# This is meant to return operators to show in the dropdown in the UI
@app.get('/operators')
def Operators(type=None):
    operators = get_operators(type)
    return operators

# This is meant to return list of transactions
@app.get('/transactions')
def Transactions():
    transactions = []
    return transactions

# This is meant to return list of rules
@app.get('/rules')
def Rules():
    rules = []
    return rules

# This is meant to return list of rules
@app.get('/autogen-rules')
def AutogeneratedRules():
    autogenerated_rules = []
    return autogenerated_rules

# Rule Model

# export type Rule = {
#     id?: number | null,
#     title: string | null,
#     description?: string | null,
#     rule: object[] | null,
#     weight: number | null,
#     autogenerated: boolean,
#     active: boolean,
#     createdAt: string | null
# }




if __name__ == "__main__":
    print('port => ', port)
    print('reload => ', reload)
    print('host => ', host)
    uvicorn.run('main:app', port=port, reload=reload, host=host)
